name: Build and deploy ASP.Net Core app to Azure Web App - ManufakturaSukcesu-Learning-App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Dodany krok diagnostyczny do sprawdzenia struktury katalogów
      - name: List files in root directory
        run: ls -la

      - name: List files in working directory LanguageLearningApp
        run: ls -la LanguageLearningApp

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'  # Upewnij się, że wersja Node.js jest kompatybilna z Twoimi zależnościami

      - name: Install npm dependencies
        working-directory: LanguageLearningApp/LanguageLearningApp  # Poprawiona ścieżka
        run: npm install

      - name: Build TailwindCSS
        working-directory: LanguageLearningApp/LanguageLearningApp  # Poprawiona ścieżka
        run: npm run css:build

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ManufakturaSukcesu-Learning-App'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_DEF1287712024FBA958AC5446E631D30 }}
