name: Deploy ASP.NET Core app to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0'

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20' # Podaj wersję Node.js, której używasz

    - name: Install npm dependencies
      run: npm install

    - name: Set permissions for tailwindcss
      run: chmod +x ./node_modules/.bin/tailwindcss

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release --no-restore

    - name: Publish project
      run: dotnet publish -c Release -o ./publish_output

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
          app-name: 'ManufakturaSukcesu-Learning-App'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_DEF1287712024FBA958AC5446E631D30 }}
